
# Fly.io config — update `app` to your unique app name before deploy
app = "cerberus-skn-z9t6k1m2q7vp"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  # SEARCH_PROVIDER can be 'dummy', 'serpapi', or 'bing'
  SEARCH_PROVIDER = "dummy"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "3s"
    grace_period = "30s"
