openapi: 3.1.0
info:
  title: Cerberus Runner (ChatGPT + Gemini)
  version: "0.4.2"
servers:
  - url: https:////fly-io-integration.fly.dev
paths: {}
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
