openapi: 3.1.0
info:
  title: Cerberus Runner (ChatGPT + Gemini)
  version: "0.4.0"
servers:
  - url: https://cerberus.fly.dev
paths:
  /health:
    get:
      operationId: health
      summary: Health check
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string }
                  ts: { type: integer }
  /run:
    post:
      operationId: runJob
      summary: Execute a Cerberus job and return a base64 ZIP
      security:
        - ApiKeyAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                run_id: { type: string, description: "Optional deterministic run ID" }
                stage: { type: string, default: "synthesis" }
                payload:
                  type: object
                  description: "Free-form job instructions/data"
      responses:
        "200":
          description: Artifact ZIP and metadata
          content:
            application/json:
              schema:
                type: object
                properties:
                  run_id: { type: string }
                  artifact:
                    type: object
                    properties:
                      filename: { type: string }
                      mime: { type: string }
                      size_bytes: { type: integer }
                      sha256: { type: string }
                      base64: { type: string, description: "Base64-encoded ZIP bytes" }
                  logs:
                    type: array
                    items: { type: string }
  /llm/gemini-test:
    get:
      operationId: geminiTest
      summary: Verify Gemini API connectivity
      security:
        - ApiKeyAuth: [ ]
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  model: { type: string }
                  text: { type: string }
  /run/gemini:
    post:
      operationId: runGemini
      summary: Use Gemini to craft content, then return a base64 ZIP
      security:
        - ApiKeyAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                run_id: { type: string }
                prompt: { type: string, default: "Summarize Cerberus in one paragraph." }
                model: { type: string, default: "gemini-2.5-flash" }
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  run_id: { type: string }
                  artifact:
                    type: object
                    properties:
                      filename: { type: string }
                      mime: { type: string }
                      size_bytes: { type: integer }
                      sha256: { type: string }
                      base64: { type: string }
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
