openapi: 3.1.0
info:
  title: Cerberus Runner Fixed
  version: "0.1.0"
servers:
  - url: https://YOUR_APP_HOST
paths:
  /run:
    post:
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: ok
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
