      - name: Create app (auto-unique, verbose) and patch fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          set -euo pipefail

          BASE="${BASE_APP_NAME:-cerberus}"
          BASE="$(echo "$BASE" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9-')"
          if [ -z "$BASE" ]; then BASE="cerberus"; fi

          try_create () {
            local NAME="$1"
            echo "Attempting to create app: $NAME"
            set +e
            # Use --verbose and capture both stdout/stderr
            OUT=$(flyctl --verbose apps create "$NAME" 2>&1)
            CODE=$?
            set -e
            echo "----- flyctl output (create $NAME) -----"
            echo "$OUT"
            echo "----- exit code: $CODE -----"
            if [ $CODE -eq 0 ]; then
              echo "$NAME"
              return 0
            fi
            # Name taken → Fly often says this exact phrase
            if echo "$OUT" | grep -qi "Not authorized to deploy this app"; then
              return 2
            fi
            # Quotas / verification / suspended org patterns (don’t fail silently)
            if echo "$OUT" | grep -Eqi "suspend|trial|verification|payment|quota|limit"; then
              echo "::error::Fly rejected app creation due to account/org status: see output above."
              return 9
            fi
            return $CODE
          }

          # Already owned?
          if flyctl apps list | tail -n +2 | awk '{print $1}' | grep -qx "$BASE"; then
            FINAL="$BASE"
            echo "App $FINAL already exists under your account."
          else
            if NAME=$(try_create "$BASE"); then
              FINAL="$NAME"
            else
              RC=$?
              if [ $RC -eq 2 ]; then
                # Name taken → add random suffix with python (no pipes)
                RAND="$(python3 -c "import secrets,string; a='abcdefghijklmnopqrstuvwxyz0123456789'; print(''.join(secrets.choice(a) for _ in range(12)))")"
                FINAL="${BASE}-${RAND}"
                echo "Name taken. Retrying with: $FINAL"
                NAME=$(try_create "$FINAL") || { echo "::error::Failed to create even with suffix (see output above)."; exit 3; }
                FINAL="$NAME"
              elif [ $RC -eq 9 ]; then
                echo "::error::Account/org may need verification or has hit a limit. Resolve in Fly dashboard, then rerun."
                exit 9
              else
                echo "::error::flyctl create failed (code $RC). See output above."
                exit $RC
              fi
            fi
          fi

          echo "FINAL_APP_NAME=$FINAL" >> "$GITHUB_ENV"

          # Patch fly.toml with final name & region
          sed -i 's/^app = ".*/app = "'"$FINAL"'"/' fly.toml
          sed -i 's/^primary_region = ".*/primary_region = "'"$FLY_PRIMARY_REGION"'"/' fly.toml

          echo "----- fly.toml (after) -----"
          grep -E '^(app|primary_region)' fly.toml || true
