
name: core-release-bundle (Parquet)
on:
  push:
    tags: ["core-v*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pyarrow+pandas
        run: |
          python -m pip install --upgrade pip
          pip install pyarrow pandas

      - name: Convert CSV→Parquet, update manifest, build report.json, package
        run: |
          python scripts/convert_to_parquet.py
          python scripts/update_manifest_to_parquet.py
          python scripts/build_report_json.py
          python scripts/package_deploy_bundle.py
          ls -la deploy_bundle.zip gold/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name || 'core-v-manual' }}
          name: Core Bundle (Parquet) ${{ github.ref_name || '(manual)' }}
          draft: false
          prerelease: false
          files: deploy_bundle.zip
